// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LeaderBoards
{
        public const string achievement_doomed = "CgkIh7LP29oSEAIQFw"; // <GPGSID>
        public const string achievement_strike = "CgkIh7LP29oSEAIQCg"; // <GPGSID>
        public const string achievement_piece_of_cake = "CgkIh7LP29oSEAIQAg"; // <GPGSID>
        public const string achievement_please_stop_hacking_for_gods_sake = "CgkIh7LP29oSEAIQBg"; // <GPGSID>
        public const string achievement_power_hungry = "CgkIh7LP29oSEAIQEQ"; // <GPGSID>
        public const string achievement_3_pointer = "CgkIh7LP29oSEAIQCA"; // <GPGSID>
        public const string achievement_shopper = "CgkIh7LP29oSEAIQEg"; // <GPGSID>
        public const string achievement_howzat = "CgkIh7LP29oSEAIQDQ"; // <GPGSID>
        public const string leaderboard_top_scores = "CgkIh7LP29oSEAIQGA"; // <GPGSID>
        public const string achievement_gold_mine = "CgkIh7LP29oSEAIQDw"; // <GPGSID>
        public const string achievement_epic_fail = "CgkIh7LP29oSEAIQFg"; // <GPGSID>
        public const string achievement_beginners_luck = "CgkIh7LP29oSEAIQAQ"; // <GPGSID>
        public const string achievement_its_a_goal = "CgkIh7LP29oSEAIQCQ"; // <GPGSID>
        public const string achievement_rollin_in_the_deep = "CgkIh7LP29oSEAIQAw"; // <GPGSID>
        public const string achievement_master_avatar = "CgkIh7LP29oSEAIQEA"; // <GPGSID>
        public const string achievement_a_penny_spent_is_a_penny_earned = "CgkIh7LP29oSEAIQEw"; // <GPGSID>
        public const string achievement_you_got_served = "CgkIh7LP29oSEAIQCw"; // <GPGSID>
        public const string achievement_disgraceful = "CgkIh7LP29oSEAIQFQ"; // <GPGSID>
        public const string achievement_hackerman = "CgkIh7LP29oSEAIQBQ"; // <GPGSID>
        public const string achievement_how_did_you_get_here = "CgkIh7LP29oSEAIQBA"; // <GPGSID>
        public const string achievement_lavish_spender = "CgkIh7LP29oSEAIQFA"; // <GPGSID>

}

